name: c15 build deploy

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Deployment environment'
        required: true
        type: choice
        options:
          - dev
          - prod
      paths:
        description: 'Path to app directory'
        required: false
        default: './class13-14/app/'

env:
  aws_region: ap-south-1
  path: ./app
  # repo: "${var.environment}-${var.app_name}-${each.key}"


jobs:
  image-build-push:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        service:
          - name: flask
            ecr_repo: ${{ github.event.inputs.environment }}-candycush-flask
            path: ./class13-14/app/
          - name: redis
            ecr_repo: ${{ github.event.inputs.environment }}-candycush-redis
            path: ./class13-14/app/redis/
          - name: nginx
            ecr_repo: ${{ github.event.inputs.environment }}-candycush-nginx
            path: ./class13-14/app/nginx/

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v5.1.1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.aws_region }}

      - name: Login to Amazon ECR
        id: login-ecr
        run: |
          aws ecr get-login-password --region ${{ env.aws_region }} | docker login --username AWS --password-stdin ${{ secrets.AWS_ACCOUNT }}.dkr.ecr.${{ env.aws_region }}.amazonaws.com

      - name: Build, tag, and push image to Amazon ECR
        run: |
          docker build -t ${{ matrix.service.ecr_repo }} ${{ matrix.service.path }}
          docker tag  ${{ matrix.service.ecr_repo }} ${{ secrets.AWS_ACCOUNT }}.dkr.ecr.${{ env.aws_region }}.amazonaws.com/${{ matrix.service.ecr_repo }}:${{ github.sha }} 
          docker tag  ${{ matrix.service.ecr_repo }} ${{ secrets.AWS_ACCOUNT }}.dkr.ecr.${{ env.aws_region }}.amazonaws.com/${{ matrix.service.ecr_repo }}:latest
          docker push ${{ secrets.AWS_ACCOUNT }}.dkr.ecr.${{ env.aws_region }}.amazonaws.com/${{ matrix.service.ecr_repo }}:${{ github.sha }}
          docker push ${{ secrets.AWS_ACCOUNT }}.dkr.ecr.${{ env.aws_region }}.amazonaws.com/${{ matrix.service.ecr_repo }}:latest