name: terraform check on PR

on:
  pull_request:
    branches:
      - main

env:
  AWS_REGION: ap-south-1
  infra_dir: ./class11-12/infra
  terraform_version: 1.8.1
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  terraform-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.terraform_version }}

      - name: tf fmt check
        run: terraform fmt --check
        working-directory: ${{ env.infra_dir }}

      - name: Initialize Terraform
        run: terraform init
        working-directory: ${{ env.infra_dir }}

      - name: Validate Terraform configuration
        run: terraform validate
        working-directory: ${{ env.infra_dir }}

      - name: Terraform plan
        run: terraform plan
        working-directory: ${{ env.infra_dir }}

      